### ISSUE TITLE
Proxy not working as expected

### ISSUE THREAD

**Issue by fayak** [pythops/tamanoir#16]
Hello !

I'm trying to run it as describe in the README, or at least something similar adapted to my configuration, but unfortunately I can't make it work.

I run the proxy:
```
$ docker run --rm -it -p 53:53/udp -e PAYLOAD_LEN=8  proxy
Starting Proxy Resolver (*:53 -> 8.8.8.8:53) [UDP]
```
then Tamanoir:
```
$ RUST_LOG=info sudo -E ./target/release/tamanoir --proxy-ip 127.0.0.1 --hijack-ip 8.8.8.8 --layout 1 --iface enp102s0f4u1u3    
Waiting for Ctrl-C...
```

My `/etc/resolv.conf` contains:
```
nameserver 8.8.8.8
```
I have multiple interfaces but I'm currently using `enp102s0f4u1u3` as shown by `ip r`: `default via 192.168.200.1 dev enp102s0f4u1u3 proto dhcp src 192.168.201.234 metric 100`

Then I try to run `host google.com` to both generate some key presses and a DNS query. The `host` command does not work, it times out:
```
;; communications error to 8.8.8.8#53: timed out
;; communications error to 8.8.8.8#53: timed out
;; no servers could be reached
```

Tamanoir logs:
```
[INFO  tamanoir::egress] 
    -----
    New intercepted request:
    -----
[INFO  tamanoir::egress]  192.168.201.234:58052 -> 127.0.0.1:53
[INFO  tamanoir::egress] 
    -----
    New intercepted request:
    -----
[INFO  tamanoir::egress]  192.168.201.234:58052 -> 127.0.0.1:53
[...]
```
without much more information, and the proxy remains silent except for the startup line I already pasted above. To me it seems like tamanoir indeed captures the DNS requests but either fails to send them to the proxy, or the proxy is misbehaving.

When I stop Tamanoir and try to reach the proxy directly:
```
$ dig google.com @127.0.0.1
;; communications error to 127.0.0.1#53: timed out
;; communications error to 127.0.0.1#53: timed out
;; communications error to 127.0.0.1#53: timed out

; <<>> DiG 9.20.3 <<>> google.com @127.0.0.1
;; global options: +cmd
;; no servers could be reached
```
proxy logs: 
```
172.17.0.1: 
2024-12-04 09:44:52 [PassthroughDNSHandler:ProxyResolver] Invalid Request: [172.17.0.1:50305] (udp) :: Error unpacking RR [offset=39]: Not enough bytes [offset=39,remaining=4,requested=12]
```

so it seems like the proxy is running and reachable.

Am I missing something here ?

**Comment by pythops** [comment]
Closing this issue
