### ISSUE TITLE
Add Docs about the proxy

### ISSUE THREAD

**Issue by Talleyrand-34** [pythops/tamanoir#22]
I want to contribute the proxy part, i don't understand hwo and why it works.

I am testing on my machine, the ebpf part works but the dns proxy is up, but i don't know what it does or how it works (i read the code but it is not clear why).

**Comment by pythops** [comment]
Basically, the dns proxy will get the dns request packet, parse it, extract the keys, send the DNS request to legitimate DNS server, and forward the response. If there is some code part you don't understand, we'll be glad to explain it more.

**Comment by pythops** [comment]
btw, we are doing some refactoring to simplify the proxy, so hopefully that will make the code more clear
